In [1]:
import numpy as np

1. Generate training data
    1. n =1000, 2 features, binary variable from Bernoulli distribution with p=0.5, features for class 0 generated independently from a normal distribution (0,1), the second (a,1). Create such datasets for many different a's
    2. n = 1000, 2 features, 2 features, Bernoulli 0.5, 2d normal dist (0,1,p), 2d normal dist (a,1,p)
2. Compare, for a =0.1,0.5,1,2,3,5, p=0.5, different train/test splits, boxplots of accuracy for each method and each parameter a.
3. Compare, a=2, p=0,0.1,0.3,0.5,0.7,0.9, different train/test splits, boxplots each method each p
4. For a=2, p = 0.5, scatter plot training set, mark observations belonging to different classes with colors and draw curves for LDA and QDA.
5. Real Data: 3 datasets from the link, binary classification
    1. compare lda, qda, nb. split data into a training set and a test set. train the model on trains et and compute accuracy on the test set, repeat for a different train, test splits, generate boxplots for each method

Formulas have been taken from lecture slides.

LDA:
1. Calculate the assumed common covariance matrix
2. Calculate the means for each of the two classes
3. Plug into the formula $f_{kl}(x)=wx+b$, when $f(x) < 0$, predicted class: $l$, else predicted class: $k$
    1. $w=(\mu_k-\mu_l)^T\Sigma^{-1}$
    2. $b=-\frac{1}{2}(\mu_k\mu_l)^T\Sigma^{-1}(\mu_k+\mu_l)+log\frac{N_k}{N_l}$
    
QDA:
1. Calculate the covariance matrix for each of the two classes
2. Calculate the means for each of the two classes
3. Plug into the formula $f(x)=sign(w^Tx+b)$
    1. $w=\Sigma^{-1}(\mu_1-\mu_{-1})$
    2. $b=\frac{1}{2}(\mu_{-1}+\mu_1)^T\Sigma^{-1}(\mu_{-1}-\mu_1)+log\frac{N_1}{N_{-1}}$
    

In [36]:
class LDA:
    def __init__(self):
        self.w=0
        self.b=0
        self.mean_0=0
        self.mean_1=0
        self.covariance_matrix=0

    def fit(self,X,y):
        classes= np.unique(y)
        self.covariance_matrix = np.cov(X[y==classes[0]].T)
        self.mean_0=np.mean(X[y==classes[0]], axis=0)
        self.mean_1=np.mean(X[y==classes[1]], axis=0)

        covariance_matrix_inverse = np.linalg.inv(self.covariance_matrix)
        no_0 = (y==classes[0]).sum()
        no_1=(y==classes[1]).sum()
        # class 0 being class k, and class 1 being class l
        self.w=(self.mean_0-self.mean_1).T.dot(covariance_matrix_inverse)
        print((self.mean_0+self.mean_1).dot(covariance_matrix_inverse))
        self.b=-(1/2)*(self.mean_0-self.mean_1).T.dot(covariance_matrix_inverse).dot((self.mean_0+self.mean_1))+np.log(no_0/no_1)

        
    def predict_proba(self, Xtest):
        f = self.w.dot(Xtest)+self.b
        print("Predicted: ",f)
        return f
    def predict(self, Xtest):
        f = np.sign(self.w.dot(Xtest)+self.b)
        print("Predicted class: ",1 if f==-1 else 0)
        return 1 if f==-1 else 0
    def get_params(self):
        print("w: ",self.w ,"\nb: ",self.b, "\nm_0: ",self.mean_0, "\nm_1: ",self.mean_1,"\ncovariance matrix: ",self.covariance_matrix)
        return (self.w, self.b,self.mean_0,self.mean_1,self.covariance_matrix)
    
class QDA:
    def fit(X,y):
        return NotImplementedError
    def predict_proba(Xtest):
        return NotImplementedError
    def predict(Xtest):
        return NotImplementedError
    def get_params():
        return NotImplementedError
    

class NB:
    def fit(X,y):
        return NotImplementedError
    def predict_proba(Xtest):
        return NotImplementedError
    def predict(Xtest):
        return NotImplementedError
    def get_params():
        return NotImplementedError
    



In [42]:
X = np.random.normal(3, 2.5, size=(10, 4))
Y = np.random.randint(2,size=10)
print(X,Y)

[[ 6.13179005  1.73842454  7.39926669  1.14517252]
 [-1.2896735   8.17346849  3.38000997  2.41484807]
 [ 3.00717123  2.78124415  4.59651867 -0.77841864]
 [ 6.84612361  4.72044843  1.46683921 -0.98261713]
 [-0.2974769   2.76191551  3.477662   12.10324243]
 [ 7.03125447  1.51015117  7.70899129  0.25178899]
 [ 3.63091488  3.60274858  2.29498817  4.64225082]
 [ 0.76931606  6.78900579 -4.50943042  0.74917708]
 [ 2.65709149  4.34121913  3.77477398  7.10477341]
 [ 2.32667944  3.4772766   3.4585569   0.35840245]] [1 0 1 0 0 0 0 1 1 0]


In [38]:
lda=LDA()

lda.fit(X,Y)
lda.get_params()

[ 6.6127228   3.01819346  6.35489036 -2.56331025]
w:  [ 0.98800239 -0.1979314   0.63877465 -0.81656575] 
b:  -3.245327417606693 
m_0:  [3.60075308 2.94371556 3.8647735  2.1053826 ] 
m_1:  [2.65684817 3.10882529 3.68790492 1.95839528] 
covariance matrix:  [[ 6.66601065 -3.90163821 -1.35902893  6.79219403]
 [-3.90163821  7.90023943 -1.95017669 -7.95912272]
 [-1.35902893 -1.95017669  4.33756721  2.00490501]
 [ 6.79219403 -7.95912272  2.00490501 11.53582477]]


(array([ 0.98800239, -0.1979314 ,  0.63877465, -0.81656575]),
 -3.245327417606693,
 array([3.60075308, 2.94371556, 3.8647735 , 2.1053826 ]),
 array([2.65684817, 3.10882529, 3.68790492, 1.95839528]),
 array([[ 6.66601065, -3.90163821, -1.35902893,  6.79219403],
        [-3.90163821,  7.90023943, -1.95017669, -7.95912272],
        [-1.35902893, -1.95017669,  4.33756721,  2.00490501],
        [ 6.79219403, -7.95912272,  2.00490501, 11.53582477]]))

In [65]:
def scheme_1_data_generator(a):
    n=1000
    bern_prob=0.5
    y=np.random.binomial(size=n, n=1, p= bern_prob)
    feature_0_0 = np.random.normal(0, 1, size=(1, n)).T
    feature_0_1 = np.random.normal(0, 1, size=(1, n)).T
    feature_0=np.hstack([feature_0_0,feature_0_1])

    feature_1_0 = np.random.normal(a, 1, size=(1, n)).T
    feature_1_1 = np.random.normal(a, 1, size=(1, n)).T
    feature_1=np.hstack([feature_1_0,feature_1_1])
    
    X = np.concatenate((feature_0[y==0],feature_1[y==1]))
    return (X,y)
def scheme_2_data_generator(mean,rho):
    n=1000
    bern_prob=0.5
    y=np.random.binomial(size=n, n=1, p= bern_prob)
    # cov(X,Y) = corr(X,Y)*std(X)*std(Y)
    features_0 = np.random.multivariate_normal([0,0], [[1,rho],[rho,1]], n)
    features_1 = np.random.multivariate_normal([mean,mean], [[1,-rho],[-rho,1]], n)
    X = np.concatenate((features_0[y==0],features_1[y==1]))
    return (X,y)


In [66]:
(X,y)=scheme_1_data_generator(2)
scheme_2_data_generator(1,0.5)

(array([[ 0.93312921, -0.43047498],
        [ 0.31244794,  0.464114  ],
        [-0.1503031 ,  0.99612549],
        ...,
        [ 1.00787493,  1.31566557],
        [ 0.45444209,  2.45992746],
        [ 1.52140319, -0.2395218 ]]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 