In [1]:
import numpy as np

1. 

Formulas have been taken from lecture slides.

LDA:
1. Calculate the assumed common covariance matrix
2. Calculate the means for each of the two classes
3. Plug into the formula $f_{kl}(x)=wx+b$, when $f(x) < 0$, predicted class: $l$, else predicted class: $k$
    1. $w=(\mu_k-\mu_l)^T\Sigma^{-1}$
    2. $b=-\frac{1}{2}(\mu_k\mu_l)^T\Sigma^{-1}(\mu_k+\mu_l)+log\frac{N_k}{N_l}$
    
QDA:
1. Calculate the covariance matrix for each of the two classes
2. Calculate the means for each of the two classes
3. Plug into the formula $f(x)=sign(w^Tx+b)$
    1. $w=\Sigma^{-1}(\mu_1-\mu_{-1})$
    2. $b=\frac{1}{2}(\mu_{-1}+\mu_1)^T\Sigma^{-1}(\mu_{-1}-\mu_1)+log\frac{N_1}{N_{-1}}$
    

In [36]:
class LDA:
    def __init__(self):
        self.w=0
        self.b=0
        self.mean_0=0
        self.mean_1=0
        self.covariance_matrix=0

    def fit(self,X,y):
        classes= np.unique(y)
        self.covariance_matrix = np.cov(X[y==classes[0]].T)
        self.mean_0=np.mean(X[y==classes[0]], axis=0)
        self.mean_1=np.mean(X[y==classes[1]], axis=0)

        covariance_matrix_inverse = np.linalg.inv(self.covariance_matrix)
        no_0 = (y==classes[0]).sum()
        no_1=(y==classes[1]).sum()
        # class 0 being class k, and class 1 being class l
        self.w=(self.mean_0-self.mean_1).T.dot(covariance_matrix_inverse)
        print((self.mean_0+self.mean_1).dot(covariance_matrix_inverse))
        self.b=-(1/2)*(self.mean_0-self.mean_1).T.dot(covariance_matrix_inverse).dot((self.mean_0+self.mean_1))+np.log(no_0/no_1)

        
    def predict_proba(self, Xtest):
        f = self.w.dot(Xtest)+self.b
        print("Predicted: ",f)
        return f
    def predict(self, Xtest):
        f = np.sign(self.w.dot(Xtest)+self.b)
        print("Predicted class: ",1 if f==-1 else 0)
        return 1 if f==-1 else 0
    def get_params(self):
        print("w: ",self.w ,"\nb: ",self.b, "\nm_0: ",self.mean_0, "\nm_1: ",self.mean_1,"\ncovariance matrix: ",self.covariance_matrix)
        return (self.w, self.b,self.mean_0,self.mean_1,self.covariance_matrix)
    
class QDA:
    def fit(X,y):
        return NotImplementedError
    def predict_proba(Xtest):
        return NotImplementedError
    def predict(Xtest):
        return NotImplementedError
    def get_params():
        return NotImplementedError
    

class NB:
    def fit(X,y):
        return NotImplementedError
    def predict_proba(Xtest):
        return NotImplementedError
    def predict(Xtest):
        return NotImplementedError
    def get_params():
        return NotImplementedError
    



In [10]:
X = np.random.normal(3, 2.5, size=(10, 4))
Y = np.random.randint(2,size=10)

In [38]:
lda=LDA()

lda.fit(X,Y)
lda.get_params()

[ 6.6127228   3.01819346  6.35489036 -2.56331025]
w:  [ 0.98800239 -0.1979314   0.63877465 -0.81656575] 
b:  -3.245327417606693 
m_0:  [3.60075308 2.94371556 3.8647735  2.1053826 ] 
m_1:  [2.65684817 3.10882529 3.68790492 1.95839528] 
covariance matrix:  [[ 6.66601065 -3.90163821 -1.35902893  6.79219403]
 [-3.90163821  7.90023943 -1.95017669 -7.95912272]
 [-1.35902893 -1.95017669  4.33756721  2.00490501]
 [ 6.79219403 -7.95912272  2.00490501 11.53582477]]


(array([ 0.98800239, -0.1979314 ,  0.63877465, -0.81656575]),
 -3.245327417606693,
 array([3.60075308, 2.94371556, 3.8647735 , 2.1053826 ]),
 array([2.65684817, 3.10882529, 3.68790492, 1.95839528]),
 array([[ 6.66601065, -3.90163821, -1.35902893,  6.79219403],
        [-3.90163821,  7.90023943, -1.95017669, -7.95912272],
        [-1.35902893, -1.95017669,  4.33756721,  2.00490501],
        [ 6.79219403, -7.95912272,  2.00490501, 11.53582477]]))